### ISSUE TITLE
Visual Studio support?

### ISSUE THREAD

**Issue by Bigbossbro08** [sandsmark/freeaoe#4]
As far as I know pcrio library doesn't support in Visual Studio. It seems everything needs to be built in MingW/Linux format. Any guide to how can I make it run in Visual Studio?

**Comment by sandsmark** [comment]
did you manage to make it work? the only CI system I run is appveyor which builds it with visual studio, and the builds from there seem to run fine with wine, at least.

I looked into replacing pcrio with something less hackish, but since it seemed to work fine for my purposes I dropped it: https://github.com/sandsmark/genieutils/tree/martin/robustdll
